title: Studieren in Leipzig
description: üá∫üá¶–Ü–Ω—Ñ–æ—Ä–º–∞—Ü—ñ–π–Ω–∏–π –ø–æ—Ä—Ç–∞–ª –ø—Ä–æ –≤–∏—â—É –æ—Å–≤—ñ—Ç—É –≤ –õ–µ–π–ø—Ü–∏–≥—É –¥–ª—è —É–∫—Ä–∞—ó–Ω—Å—å–∫–∏—Ö —Å—Ç—É–¥–µ–Ω—Ç—ñ–≤\n Informationsseite f√ºr die Ukrainer, die an den Universit√§ten in Leipzig studieren wollen
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme

header_pages:
 - index.md