title: Studieren in Leipzig
description: "ğŸ‡ºğŸ‡¦ Ğ†Ğ½Ñ„Ğ¾-Ğ¿Ğ¾Ñ€Ñ‚Ğ°Ğ» Ğ´Ğ»Ñ ÑƒĞºÑ€Ğ°Ñ—Ğ½ÑÑŒĞºĞ¸Ñ… ÑÑ‚ÑƒĞ´ĞµĞ½Ñ‚Ñ–Ğ² Ñƒ Ğ›ĞµĞ¹Ğ¿Ñ†Ğ¸Ğ³Ñƒ | ğŸ‡©ğŸ‡ª Informationsseite fÃ¼r ukrainische Studierende in Leipzig"
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme

header_pages:
 - index.md